### ISSUE TITLE
Feature: Governance Proposal submission

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#1092]
## Background
On-chain governance is an important part of being involved in the Crypto.org chain ecosystem, which allows CRO holders to participate in the decision-making processes of the ecosystem development. A governance proposal usually includes a request for a code/parameter change on the blockchain network/protocol, which will be executed if passed by the community voting. 

Currently, bonded CRO holders can cast votes on active governance proposals and view previous proposals in the Governance section on Desktop Wallet. We plan to add the support for governance proposals submission, where users will be able to submit a proposal for community voting if it meets the minimum requirements for CRO deposits. The current proposal process is supported by chain-maind wallet only without a GUI, so we aim to provide an easy-to-use UI for the chain users. Additionally, we will support viewing the voting history in response to community feedback. 

## Task 

- [ ] Submit a governance proposal
- [ ] Deposit to a governance proposal
- [ ] View voting history
