### ISSUE TITLE
Feature: Timeout on password entry

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#1111]
## Background
There’s always a dilemma between security & convenience. While enforcing every transactions to input password increases security, which also creates inconvenience among users. 

We shall strike a balance.

## Suggestion
Within a suggested period of time (e.g. 10 mins) after every successful transaction, we shall allow users broadcast a transaction without entering the password again

## Task
- [ ] The decrypted phrase / password shall be stored across the wallet, and remain usable until expiration
- [ ] Above of every transaction confirmation button, there's an option for user to checkout whether to skip password entry for certain period of time
- [ ] Upon expiration, the stored decrypted phrase / password shall be removed
