### ISSUE TITLE
Governance proposal submission

### ISSUE THREAD

**Issue by JJWW34** [crypto-com/chain-desktop-wallet#1142]
## Prerequisite
- #1143 
## Background
We're looking into support Text Proposal submission on Desktop Wallet in Phase 1. In order to prevent spam proposal submissions, we enforce users to have an initial deposit of 1000 CRO from our client side. 

## Task
- [x] Implement Governance Proposal Creation modal
- [x] Form Validation on minimum 1000CRO initial deposit
- [x] Integrate API `signSubmitTextProposalTransaction()` with frontend modal
- [x] Implement Deposit Proposal workflow
- [x] Integration API `signProposalDepositTransaction()` with frontend modal
