### ISSUE TITLE
Add Notifications section

### ISSUE THREAD

**Issue by JJWW34** [crypto-com/chain-desktop-wallet#1145]
## Study
- The behavior of Electron notification (https://www.electronjs.org/docs/latest/tutorial/notifications)
- Anything need to handle for silent mode in different OS (https://github.com/felixrieseberg/electron-notification-state)
- Whether we need a mailbox for users to revisit the notifications / messages or not
- When & where shall we push notifications to users
  - After any successful transactions
  - When token balances updated

## Task
- [x] https://github.com/crypto-com/chain-desktop-wallet/issues/1196
- [ ] Implement notifications in various necessary places
- [ ] Decide if we need an external endpoint to push notifications to users

**Comment by calvinaco** [comment]
Mockup ETA: 19 July
