### ISSUE TITLE
Live CS service integration

### ISSUE THREAD

**Issue by JJWW34** [crypto-com/chain-desktop-wallet#1146]
## Background
Integrate the existing Live CS messenger at Help Center in Desktop Wallet. 

## Prerequisite
- #1145 

## Study
- Locate the detail of Live Chat API endpoint 
- The integration method:
  - Importing an iframe directly into a component
  - Importing a JS script & it creates the Live CS messenger for us
- [x] Can we keep the chat session so that users can come back & revisit the conversation
- [x] See if we could grab the response from Live Chat and push notifications to users
- Where to show the Live CS messenger

## Task
- [ ] Implement frontend chatbox messenger
- [ ] Integrate with the API endpoint
- [ ] Integrate the response from Live Chat to Notification
