### ISSUE TITLE
Implement Deposit Proposal workflow

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-desktop-wallet#1156]
## Screenshots
Please refer to Figma for detail
![Image](https://user-images.githubusercontent.com/74586409/178216878-9e9f6805-f241-4bb9-852b-dab6eb855f8b.png)

## Task
- [x] Deposit section on the right as the entry point of Deposit of any `Deposit` stage Proposal
- [x] Deposit amount verification 
  - Maximum deposit amount = ([Mainnet] 10000 CRO  or [Testnet] 20000 CRO) - Sum of current deposit inside the proposal)
- [x] Deposit Confirmation modal
