### ISSUE TITLE
Feature: Integrate a Token Price chart in Token Detail Page

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#1159]
## Main Task
- #1157 
## Tasks
- [x] Locate and integrate a chart plotting library in visualizing the token price view
- [x] The chart shall support displaying token price in different selected time period
- [x] Use the default line chart layout provided by the library, with only adjusting the color into a bluish theme fitting our DeFi Desktop Wallet
- [x] A selection of time period button on the top-right corner above a chart: e.g. 8H,1D,1W,1M,3M,6M.
- [x] The chart will change accordingly when any time period button is clicked
- [x] Hovering any point along the line in the chart will display the price at that point
- [x] The price chart shall put inside under the Token Detail section

Optional: Display 24h price change in %
