### ISSUE TITLE
Feature: Integrate Bridge Indexing service for ATOM bridge Cosmos <-> Cronos

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#1173]
## Main Issue
- #1144 
## Task
- [x] Locate the API endpoint service
  - Bridge Transfer List: `https://cronos.org/indexing/api/v1/bridges/${sourceChain}/account/${address}/activities?order=sourceBlockTime.desc`
  - Bridge Tx detail by TxHash: `https://cronos.org/indexing/api/v1/bridges/txs/${transactionHash}`
- [x] Merge the fetched Cosmos <-> Cronos bridge transfer history together with Crypto.org <-> Cronos history list
- [x] Display bridge tx detail for Cosmos <-> Cronos bridge transfer
