### ISSUE TITLE
Feature: Update UX for ATOM bridge Cosmos <-> Cronos

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#1174]
## Main Issue
- #1144 
## Task
- [x] Apply `Cosmos <-> Cronos` bridge transfer config settings
- [x] Implement different Asset selection according to different bridge transfer direction pair
- [x] Validation on `Amount` with different assets
- [x] Validation on `Address` with different chains
- [x] Fix any other unforeseeable UX mis-behavior after adding `Cosmos <-> Cronos` bridge transfer direction
