### ISSUE TITLE
Feature: Broadcast transaction of ATOM Bridge Transfer Cosmos <-> Cronos

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#1175]
## Main Issue
- #1144 

## Task
- [x] Add `Cosmos <-> Cronos` bridge transfer config settings
- [x] Add customization capability for ATOM bridge transfer `Cosmos <-> Cronos` in function `updateBridgeConfiguration()`
- [x] Apply `Cosmos <-> Cronos` Bridge configs to broadcast bridge transfer transaction
  - [x] Cosmos -> Cronos
  - [x] Cronos -> Cosmos
