### ISSUE TITLE
Feature: Ledger support for ATOM Bridge Transfer Cosmos <-> Cronos

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#1176]
## Main Issue
- #1144

## Task
- [x] Construct proper Amino Message for Ledger to sign
- [x] Broadcast the Ledger messages
- [x] Update UX for Ledger confirmation flow support
