### ISSUE TITLE
Release: Preparation for v1.1.0 Release

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#1177]
## Task
- [x] Update CHANGELOG
- [x] Handover build internal release to QA 
- [x] Fix any reported QA issues
- [x] Properly provide Release files & signed materials
- [x] Double check with Release status
