### ISSUE TITLE
Merge ethereum-integration & its based branches into dev

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#1178]
## Branches
- cosmos-integration
- feat/wallet-connect

## Task
- [x] https://github.com/crypto-com/chain-desktop-wallet/pull/1163
- [x] https://github.com/crypto-com/chain-desktop-wallet/pull/1167
- [x] https://github.com/crypto-com/chain-desktop-wallet/pull/1188
- [x] https://github.com/crypto-com/chain-desktop-wallet/pull/912
