### ISSUE TITLE
[Update]  Implement an auto-updater mechanism for newer releases

### ISSUE THREAD

**Issue by crypto-3dd** [crypto-com/chain-desktop-wallet#548]
### Tasks

- [x] 1. Find the right tool or library that works best for our packaged binaries and supports fairly well the 3 platforms if not at least 2 platforms among Windows, Linux, macOS.
- [x] 2. Publish a sample release and update the pipeline to provide expected types of binaries by the updated tools.
- [x] 3. Implement check for updates availability.
- [x] 4. Communicate events of available updates from the Electron process to the renderer process.
- [ ] 5. Handle update events and procedural download of updates chunks.
- [ ] 6. Resolve the issue of hash mismatch after download binary events electron-userland/electron-builder#5940.
- [ ] 7. Prepare a test release which auto-updater feature flag : The goal is to investigate if a signed binary would behave as expected with the auto-updater
- [ ] 8. Make quit and restart after update install optional, provide an optional restart now button: https://github.com/crypto-com/chain-desktop-wallet/pull/573
- [ ] 9. QA test auto-updater on Windows : https://github.com/crypto-com/chain-desktop-wallet/issues/577

**Comment by RainbowMiner** [comment]
Yes, please!

**Comment by eddycpc** [comment]
### Issue 1 

There was one blocking issue with the stable version of electron updater https://github.com/electron-userland/electron-builder/issues/5940.

It seems to be detecting new versions well but when it has to replace the binary, the checksum match fails.

<img width="1288" alt="Screen Shot 2021-07-06 at 12 48 14 AM" src="https://user-images.githubusercontent.com/73159521/124714950-12531080-df0b-11eb-8843-6d700b9cfb6c.png">

```
00:48:24.566 › Error: Error: sha512 checksum mismatch, expected Hq81Ata0vPJuzYeThT0w/m445aEUrhub9bXXGAkbx0komXkGNYHPWtzhN0dZKKKFlnGBcc0irfZ9ZeFezpj04A==, got GbsnNsI5HCS3kqSo99p2XTTtVT5aX3Lu1Gpk420fMEoxiveRpi+rnAHUh9+GqOnhgLev85Ntp8VJr017LjQHMw==
    at Object.newError (/Applications/Crypto.org Chain Desktop Wallet (Beta).app

```

**Comment by eddycpc** [comment]
### Issue 2

Possible blank screen as shown above when adding auto-updater hooks

**Comment by eddycpc** [comment]
### Issue 3

Related to issue 1 above, if we updater auto-updater to the latest version with fixes on hash mismatch we are likely going to run through a library incompatibility breaking change related to fs streams being used in later versions of the auto updater.

https://github.com/electron-userland/electron-builder/issues/6000

**Comment by eddycpc** [comment]
### Progress

Updates events can now be logged, listened and passed to the render process, [WIP]

https://github.com/crypto-com/chain-desktop-wallet/pull/559/commits/dc5cc2529aee0becfedf2892bcf1d4fb293d3cb5

<img width="1310" alt="Screen Shot 2021-07-07 at 1 09 45 PM" src="https://user-images.githubusercontent.com/73159521/124742436-6539c180-df25-11eb-8a7c-c1711f2ff40e.png">

**Comment by eddycpc** [comment]
PR available now for task 1 to 4 : https://github.com/crypto-com/chain-desktop-wallet/pull/559
